$(document).ready(function () {
    // Defining the local dataset

    var freelancers = ['Accountant',
'Acting Extra',
'Actor',
'Admin Assistant',
'Animator',
'Architect',
'Author',
'Baby Planner',
'Baby Proofer',
'Babysitter',
'Birthday Party Planner',
'Bitcoin Trader',
'Blogger',
'Boat Master',
'Body Guard',
'Boxing Coach',
'Braai Master',
'Brand Advocate',
'Business Incubator',
'Business Manager',
'Business Plan Assistant',
'Business Strategist',
'Cake baker',
'Caretaker, Old Aged',
'Carpenter',
'Chauffeur',
'Choral Director',
'Choreographer',
'Collect & Deliver',
'Comedian',
'Copywriter',
'Dance Therapist',
'Dancer, Contemporary',
'Dancer, Traditional',
'Data Analyst',
'Dietician',
'Dog Trainer',
'Dog Walker',
'Drummist',
'Editor',
'Electrician',
'Errands Runner',
'Events Decorator',
'Events DJ',
'Events MC',
'Events Planner',
'Events Promoter ',
'Events Usher',
'Face Painter',
'Farm Advisor',
'Fashion Designer',
'Fashion Model',
'Film & TV producer',
'Financial Advisor',
'Fish Farm Advisor',
'Fitness Trainer',
'Flight Attendant',
'Floor Specialist ',
'Foreign Student Advisor',
'Forex Trader',
'Google Services Advisor ',
'Graphic Designer',
'Guitarist',
'Hairdresser',
'High School Tutor',
'Home Call Centre Rep',
'Home Car washer',
'Home Schooler',
'House Cleaner',
'House Keeper',
'Impersonator',
'Instagram Marketer',
'Insurance Advisor',
'Interior Designer',
'Interview Host',
'Knitter',
'Landscape Designer',
'Language Translator',
'Laptop & Phone Repairer',
'Lawn/Garden Caretaker',
'Legal Advisor',
'Livestock Advisor',
'Locksmith',
'Logistics Assistant',
'Makeup Artist',
'Manicure & Pedicurist',
'Market Researcher',
'Marketing Assistant',
'Massage Therapist',
'Medical Transcriptionist',
'Motivational Speaker',
'Music Producer',
'Music Video Producer',
'Musical Band',
'Musical Instrument Coach',
'Nurse Case Worker',
'Nurse, Midwife ',
'Part-time Receptionist',
'Patent Agent',
'Personal Assistant',
'Pet Groomer',
'Pet Sitter',
'Photographer',
'Pianist',
'Picker & Packer',
'Pilot',
'Plumber',
'Primary School Tutor',
'Private Chef',
'Private Investigator',
'Proof Reader',
'Real Estate Agent',
'Referee',
'Rental Agent',
'Sales Agent',
'School Sports Coach',
'Screenplay Writer',
'Shoe wash & Repairer',
'Sketch & Portrait Artist',
'Soccer/ Football coach',
'Social Media Marketer',
'Software Developer',
'Solo Artist',
'Song Writer & Seller',
'Statistician',
'Surfing Coach',
'Swim Coach',
'Tailor',
'Tattoo Artist',
'Teacher Assistant',
'Team Builder',
'Tech Support Specialist',
'Technician',
'Tennis Coach',
'Transcriber',
'Travel Guide',
'Tutor, Hearing Impaired',
'Tutor, Sign Language',
'Tutor, Visually Impaired',
'Umpire',
'University Tutor',
'Virtual Assistant',
'Voice Over',
'Volunteer',
'Waiter',
'Waitress',
'Wall Painter',
'Wedding planner',
'Writer',
'Yoga Instructor'];
    var freelancers = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: freelancers
    });

    // Initializing the typeahead
    $('.typeaheadFreelancers').typeahead({
        hint: true,
        highlight: true, /* Enable substring highlighting */
        minLength: 1 /* Specify minimum characters required for showing result */
    },
    {
        name: 'freelancers',
        source: freelancers
    });

    //Universities
    var places = [
        'Westdene, Johannesburg, South Africa',
        'Brixton, Johannesburg, South Africa',
        'Melville, Johannesburg, South Africa',
        'Braamfontein, Johannesburg, South Africa'
    ];//End of universities

    // Constructing the suggestion engine
    var places = new Bloodhound({
        datumTokenizer: Bloodhound.tokenizers.whitespace,
        queryTokenizer: Bloodhound.tokenizers.whitespace,
        local: places
    });

    // Initializing the typeahead
    $('.typeaheadPlaces').typeahead({
        hint: true,
        highlight: true, /* Enable substring highlighting */
        minLength: 1 /* Specify minimum characters required for showing result */
    },
    {
        name: 'places',
        source: places
    });
});